UP = 0
DOWN = 1
RIGHT = 2
LEFT = 3

HIGHIER_PROBABILITY = 10

INTERSECTION_PENALTY = 20
SUM_OF_SEGMENTS_PENALTY = 3
OUT_OF_BOARD_LENGTH_PENALTY = 30
OUT_OF_BOARD_SEGMENTS_PENALTY = 30


ROULETTE_EPSILON = 1

TOURNAMENT_SIZE = 10

CROSSOVER_PROBABILITY = 0.75
UNIFORM_CROSSOVER_PROBABILITY = 0.5

MUTATION_PROBABILITY = 0.05

PATH_MOVEMENT_SIZE = 1 # Size of movement in path mutation